import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAddBin } from "@/hooks/useBins";
import { useHouseholds } from "@/hooks/useHouseholds";
import { useCollectionPoints } from "@/hooks/useCollectionPoints";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";

interface BinCreateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  zoneId: string;
}

export const BinCreateDialog = ({ open, onOpenChange, zoneId }: BinCreateDialogProps) => {
  const [assignTo, setAssignTo] = useState<"household" | "island">("household");
  const [binType, setBinType] = useState("general");
  const [householdId, setHouseholdId] = useState("");
  const [collectionPointId, setCollectionPointId] = useState("");
  
  const addBin = useAddBin();
  const { data: households } = useHouseholds(zoneId);
  const { data: collectionPoints } = useCollectionPoints(zoneId);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    await addBin.mutateAsync({
      household_id: assignTo === "household" ? householdId : null,
      collection_point_id: assignTo === "island" ? collectionPointId : null,
      bin_type: binType,
      status: "active",
      fill_level: 0,
      last_collection: null,
      qr_code: '', // Will be auto-generated by trigger
    });

    setBinType("general");
    setHouseholdId("");
    setCollectionPointId("");
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create New Bin</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label htmlFor="binType">Bin Type</Label>
            <Select value={binType} onValueChange={setBinType}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="general">General Waste</SelectItem>
                <SelectItem value="recycling">Recycling</SelectItem>
                <SelectItem value="organic">Organic</SelectItem>
                <SelectItem value="glass">Glass</SelectItem>
                <SelectItem value="paper">Paper</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label>Assign To</Label>
            <RadioGroup value={assignTo} onValueChange={(v) => setAssignTo(v as "household" | "island")}>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="household" id="household" />
                <Label htmlFor="household" className="font-normal cursor-pointer">Household</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="island" id="island" />
                <Label htmlFor="island" className="font-normal cursor-pointer">Trash Island</Label>
              </div>
            </RadioGroup>
          </div>

          {assignTo === "household" && (
            <div>
              <Label htmlFor="household-select">Select Household</Label>
              <Select value={householdId} onValueChange={setHouseholdId}>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a household" />
                </SelectTrigger>
                <SelectContent>
                  {households?.map((household) => (
                    <SelectItem key={household.id} value={household.id}>
                      {household.address}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {assignTo === "island" && (
            <div>
              <Label htmlFor="island-select">Select Trash Island</Label>
              <Select value={collectionPointId} onValueChange={setCollectionPointId}>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a trash island" />
                </SelectTrigger>
                <SelectContent>
                  {collectionPoints?.map((point) => (
                    <SelectItem key={point.id} value={point.id}>
                      {point.name} ({point.current_bins}/{point.capacity} bins)
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button 
              type="submit" 
              disabled={(assignTo === "household" && !householdId) || (assignTo === "island" && !collectionPointId)}
            >
              Create Bin
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};
